#!/bin/bash
logsdir=$(pwd)/../../logs/*.log
resdir=$(pwd)/../../results/file_bash.log

if [ -f $logsdir ];then
ls $logsdir >> $resdir
echo '--Number of POST:' >> $resdir
grep POST $logsdir | wc -l | awk '{print $ "\n"}' >> $resdir
echo '' >> $resdir
else
echo 'No logs found for post_req'
fi

