#!/bin/bash
logsdir=$(pwd)/../../logs/*.log
resdir=$(pwd)/../../results/file_bash.log

if [ -f $logsdir ]; then
ls $logsdir >> $resdir
echo '--TOP server error:' >> $resdir
cat $logsdir | awk '{print $7,$9, $1}' | grep -w 5[0-2][0-9] | sort | uniq -c | awk '{print length($2) " " $0}'| sort -nr | awk '{print $3, $4, $5, $2}' | head  >> $resdir
echo '' >> $resdir
else
echo 'No logs found for top_server_error'
fi
